### ISSUE TITLE
カスタムテーマを保存できないバグの修正

### ISSUE THREAD

**Issue by Robot-Inventor** [Robot-Inventor/ORIZIN-Agent-HTML#78]
CSS変数の個数が変わったのにtheme.pyが対応しておらず、カスタムテーマを保存しようとするとエラーが起きる。そのため、theme.pyを以下のように修正する。あるいは、引数をリストではなく辞書にして、CSS変数の個数のチェックを省略する。

```diff
def write_custom(value: list[str]) -> None:
-   if len(value) == 5:
+   if len(value) == 7:
        custom_css_data = "/* カスタムテーマ */\n\n:root {\n    --bg: " + value[0] + ";\n    --card_bg: " + value[1] + ";\n    --text: " + \
                          value[2] + ";\n    --shadow: " + value[3] + \
            ";\n    --theme_color: " + value[4] + ";\n    --header_background_color: " + \
            value[5] + ";\n    --error_text_color: " + value[6] + ";\n}"
        with open("resource/css/theme/user/custom_theme.css", mode="w", encoding="utf-8_sig") as f:
            f.write(custom_css_data)
        return
    else:
        core.show_error("カスタムCSSテーマに不正な値を書き込もうとしています。")
        return
```

また、それに加えてtheme.pyのcurrent()で、CSS中の``-``をすべて削除してしまっている。それによって、カスタムテーマのもととなるCSSが次のようなとき

```css
:root {
    --bg: #ffffff;
    --card_bg: #ffffff;
    --text: rgba(0, 0, 0, 0.87);
    --shadow: rgba(0, 0, 0, 0.26);
    --theme_color: #f86806;
    --header_background_color: var(--theme_color);
    --error_text_color: #b00020;
}
```

次のように``-``が取り除かれてCSS変数が正しく機能しなくなる。

```css
:root {
    --bg: #ffffff;
    --card_bg: #ffffff;
    --text: rgba(0, 0, 0, 0.87);
    --shadow: rgba(0, 0, 0, 0.26);
    --theme_color: #f86806;
    --header_background_color: var(theme_color);  /* var(--theme_color)でないと動かない */
    --error_text_color: #b00020;
}
```
